<?php

phpgw::import_class('booking.uirescategory');

class bookingfrontend_uirescategory extends booking_uirescategory
{

	public $public_functions = array
	(
		'show' => true,
		'edit' => true,
		'index' => true,
	);

	protected $module;

	public function __construct()
	{
		parent::__construct();
		$this->module = "bookingfrontend";
	}

	public function index()
	{
		if (phpgw::get_var('phpgw_return_as') == 'json')
		{
			return $this->query();
		}
		phpgw::no_access();
	}

	public function show()
	{
		$config = CreateObject('phpgwapi.config', 'booking');
		$config->read();
		$id = phpgw::get_var('id', 'int');

		$session_org_id = phpgw::get_var('session_org_id');

		if(!$id && $session_org_id)
		{
			$id = CreateObject('bookingfrontend.uirescategory')->get_orgid($session_org_id);
		}
		phpgwapi_jquery::load_widget("core");

	}

	public function edit()
	{
		parent::edit(); // TODO: Change the autogenerated stub
	}
}

